# Based on https://github.com/breerly/fig-mesos
# Note: use links: as a dependency graph for now, until https://github.com/docker/fig/pull/686 is resolved
#
# Zookeeper
#
# https://hub.docker.com/r/jplock/zookeeper/
#
zk1:
  image: jplock/zookeeper:3.4.7

#
# Mesos master
#
# https://hub.docker.com/r/hervenicol/docker-mesos/
# http://mesos.apache.org/documentation/latest/configuration/
#
mesos1:
  image: hervenicol/docker-mesos-master:0.26
  ports:
    - "5050:5050"
  links:
    - "zk1:zookeeper1"
  environment:
    MESOS_LOG_DIR: /var/log
    MESOS_CLUSTER: localmesos
    MESOS_ZK: zk://zookeeper1:2181/mesos
    MESOS_HOSTNAME: 192.168.1.38
    MESOS_WORK_DIR: /var/lib/mesos
    MESOS_QUORUM: 1

#
# Mesos slaves
#
# https://hub.docker.com/r/hervenicol/docker-mesos/
# http://mesos.apache.org/documentation/latest/configuration/
#
slave1:
  image: hervenicol/docker-mesos-slave:0.26
  ports:
    - "5051:5051"
  links:
    - "zk1:zookeeper1"
    - "mesos1"
  environment:
    MESOS_MASTER: zk://zookeeper1:2181/mesos
    MESOS_ISOLATOR: "cgroups/cpu,cgroups/mem"
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: "5mins"
    MESOS_HOSTNAME: 192.168.1.38
    MESOS_PORT: "5051"
    MESOS_LOG_DIR: /var/log
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/local/bin/docker:/usr/local/bin/docker
    - /sys/fs/cgroup:/sys/fs/cgroup
  command: ""
slave2:
  image: hervenicol/docker-mesos-slave:0.26
  ports:
    - "5052:5052"
  links:
    - "zk1:zookeeper1"
    - "mesos1"
  environment:
    MESOS_MASTER: zk://zookeeper1:2181/mesos
    MESOS_ISOLATOR: "cgroups/cpu,cgroups/mem"
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: "5mins"
    MESOS_HOSTNAME: 192.168.1.38
    MESOS_PORT: "5052"
    MESOS_LOG_DIR: /var/log
  volumes_from:
    - "slave1"
  command: ""
slave3:
  image: hervenicol/docker-mesos-slave:0.26
  ports:
    - "5053:5053"
  links:
    - "zk1:zookeeper1"
    - "mesos1"
  environment:
    MESOS_MASTER: zk://zookeeper1:2181/mesos
    MESOS_ISOLATOR: "cgroups/cpu,cgroups/mem"
    MESOS_CONTAINERIZERS: "docker,mesos"
    MESOS_EXECUTOR_REGISTRATION_TIMEOUT: "5mins"
    MESOS_HOSTNAME: 192.168.1.38
    MESOS_PORT: "5053"
    MESOS_LOG_DIR: /var/log
  volumes_from:
    - "slave1"
  command: ""

#
# Marathon
#
# https://hub.docker.com/r/mesosphere/marathon/
#
marathon:
  image: mesosphere/marathon:v0.13.0
  ports:
    - "4041:8080"
  links:
    - "zk1:zookeeper1"
    - "mesos1"
  command: "--master zk://zookeeper1:2181/mesos --zk zk://zookeeper1:2181/marathon"

#
# Chronos
#
# https://hub.docker.com/r/mesosphere/chronos
#
chronos:
  image: mesosphere/chronos:chronos-2.4.0-0.1.20151007110204.ubuntu1404-mesos-0.26.0-0.2.145.ubuntu1404
  ports:
    - "4040:8080"
  links:
    - "zk1:zookeeper1"
    - mesos1
  command: "/usr/bin/chronos --master zk://zookeeper1:2181/mesos --zk_hosts zk://zookeeper1:2181/mesos"
